Numerous Bug Fixes
pmmp/BedrockProtocolDumper pull request #3
Opened 2022-09-20 21:29 UTC by DJStompZone

Was not working in any sense of the word on python 3.10, fixed at least a dozen bugs and restored to working order. Though I'm sure there's things I will have missed, but it runs from start to finish now, so that's progress!

2022-09-22 04:10 UTC, SOF3 commented
the commit title is not accurate. these are not "bugs". they are completely fine with python2.

2022-09-22 05:26 UTC, DJStompZone commented
Cool, if I meet any time travelers from 2008 when that was relevant they will be delighted to hear it. In the meantime, feel free to use the version I fixed to work on versions of python under the age of 13. ✌️

2022-09-22 08:04 UTC, SOF3 commented
What I'm saying is that the purpose of this PR is to migrate to python3, not to fix bugs, because they are not bugs at all if you used the correct tools to run it. It is like trying to run a bash script with php and claiming that the bash script doesn't work because php doesn't interpret it properly.

2022-09-22 08:07 UTC, SOF3 requested changes

2022-09-22 08:07 UTC, SOF3 commented on protocol_info_generator_objdump.py
> +    return results == [True]*len(list_of_paths)
simplify this to `all(os.path.exists(path) for path in list_of_paths)`?

2022-09-22 08:11 UTC, SOF3 commented
to be clear, I am personally totally fine with this PR. I am just pointing out that python2 and python3 are basically two different languages, so it is not technically a "bug" in this sense, but it is still totally reasonable to update to python3 if someone wants to maintain it.

2022-11-11 16:10 UTC, SOF3 approved these changes

2022-11-12 14:35 UTC, dktapps requested changes
This PR contains multiple changes that are not related in any way to a python3 migration. I'm not against most of them, but they don't belong in this PR and should be done separately.

2022-11-12 14:35 UTC, dktapps commented on protocol_info_generator.py
> +    print(f"Collected {len(out.values())} packet definitions\n")
This change appears unrelated to the topic of the PR

2022-11-12 14:35 UTC, dktapps commented on protocol_info_generator_objdump.py
> +if __name__ == "__main__":
This change doesn't seem related to the topic of the PR

2022-11-12 14:35 UTC, dktapps commented on protocol_info_generator_objdump.py
> +    raise Exception(f"Invalid arguments provided:{sys.argv[1:3]} check that the paths are correct")
This change is not related to the PR topic

2022-11-12 14:35 UTC, dktapps commented on protocol_info_generator.py
> +        fp.write(json.dumps({f"v{str(version).split(' ')[-1]}": out}))
This change is not related to the PR topic

2022-11-12 21:41 UTC, DJStompZone commented
That's why the original topic was "numerous bug fixes", as these were simply the changes required to successfully execute BedrockProtocolDumper on my machine with a modern version of python.
Seems like a silly and pedantic thing to quibble about though, really. It could be called "double cheeseburger and medium fry", and the code would still run exactly the same, so... Who cares what the title is?

2022-11-12 21:43 UTC, dktapps commented
The title isn't really the point. Generally speaking it's bad PR or commit hygiene to put multiple unrelated changes into the same PR or commit.

2022-11-13 17:34 UTC, SOF3 commented
as a quick script that was not in a well maintained state, usually "code cleanup" is not efficient and understandable than atomic commits, especially when you most likely won't want to roll back small parts of the commit.

2024-10-26 15:44 UTC, dktapps commented
This PR (and repository) has been superseded by the improved version of the tool in [bds-modding-devkit](https://github.com/pmmp/bds-modding-devkit) which uses Python 3 and generates JSON data instead of PHP code.

2024-10-26 15:44 UTC, closed without merging